// export const TOGGLE_DARKNESS = 'TOGGLE_DARKNESS';
export const [
START_GAME, 
PLAYER_WON, 
PLAYER_LOST,
TOGGLE_DARKNESS,
PLAYER_HP_UP,
PLAYER_HP_DOWN,
LEVEL_UP,
ATTACK_UP,
WEAPON_UP,
MOVE,
ENEMY_HP_DOWN,
ENEMY_KILLED,
BOSS_HP_DOWN ] = [
"START_GAME",
"PLAYER_WON", 
"PLAYER_LOST",
"TOGGLE_DARKNESS",
"PLAYER_HP_UP",
"PLAYER_HP_DOWN",
"LEVEL_UP",
"ATTACK_UP",
"WEAPON_UP",
"MOVE",
"ENEMY_HP_DOWN",
"ENEMY_KILLED",
"BOSS_HP_DOWN"
]
